apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dotnet-github-actions-nexus-ga-030425 
  janus-idp.io/tekton: dotnet-github-actions-nexus-ga-030425
  backstage.io/kubernetes-id: dotnet-github-actions-nexus-ga-030425
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet-github-actions-nexus-ga-030425
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml