apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet-github-actions-nexus-ga-030425
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet-github-actions-nexus-ga-030425 
  name: dotnet-github-actions-nexus-ga-030425
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dotnet-github-actions-nexus-ga-030425
    weight: 100 
