apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet-github-actions-nexus-ga-030425
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet-github-actions-nexus-ga-030425 
  name: dotnet-github-actions-nexus-ga-030425
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnet-github-actions-nexus-ga-030425 
